In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('synthetic_logs.csv')
df.head(5)

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [3]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [4]:
df.target_label.unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [6]:
%pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-6.0.1-py3-none-any.whl.metadata (20 kB)
Collecting transformers<6.0.0,>=5.0.0 (from sentence-transformers)
  Downloading transformers-5.17.0-py3-none-any.whl.metadata (32 kB)
Collecting tokenizers>=0.19 (from sentence-transformers)
  Downloading tokenizers-0.23.2-cp310-abi3-win_amd64.whl.metadata (10 kB)
Collecting huggingface-hub<2.0.0,>=1.3.0 (from sentence-transformers)
  Downloading huggingface_hub-1.31.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: torch>=2.2 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sentence-transformers) (2.7.1+cu118)
Requirement already satisfied: numpy>=1.24.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=1.1.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sentence-transformers) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.10.0 in C:\Users\Moolya\AppData\Roaming\Python\Python311\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sentence-transformers) (4.68.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.4.0)
Collecting hf-xet<2.0.0,>=1.5.2 (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers)
  Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: colorama in C:\Users\Moolya\AppData\Roaming\Python\Python311\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.4.6)
Requirement already satisfied: anyio in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: regex>=2025.10.22 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2026.7.19)
Requirement already satisfied: typer in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.27.1)
Collecting safetensors>=0.8.0 (from transformers<6.0.0,>=5.0.0->sentence-transformers)
  Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.6.0)
Requirement already satisfied: sympy>=1.13.3 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch>=2.2->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Moolya\AppData\Roaming\Python\Python311\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=5.0.0->sentence-transformers) (0.1.2)
Downloading sentence_transformers-6.0.1-py3-none-any.whl (739 kB)
   ---------------------------------------- 0.0/739.8 kB ? eta -:--:--
   -------------- ------------------------- 262.1/739.8 kB ? eta -:--:--
   ---------------------------------------- 739.8/739.8 kB 1.8 MB/s  0:00:00
Downloading huggingface_hub-1.31.0-py3-none-any.whl (798 kB)
   ---------------------------------------- 0.0/798.3 kB ? eta -:--:--
   ------------- -------------------------- 262.1/798.3 kB ? eta -:--:--
   -------------------------- ------------- 524.3/798.3 kB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 798.3/798.3 kB 1.5 MB/s  0:00:00
Downloading hf_xet-1.6.0-cp38-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 1.9 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/4.0 MB 1.9 MB/s eta 0:00:02
   --------------- ------------------------ 1.6/4.0 MB 1.9 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 2.3 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 2.5 MB/s  0:00:01
Downloading transformers-5.17.0-py3-none-any.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 2.8 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/12.3 MB 3.4 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.3 MB 3.4 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.3 MB 3.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.4/12.3 MB 3.4 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.3 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.3 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.3 MB 3.4 MB/s eta 0:00:03
   ---------------- ----------------------- 5.0/12.3 MB 2.8 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.3 MB 2.9 MB/s eta 0:00:03
   --------------------- ------------------ 6.6/12.3 MB 2.9 MB/s eta 0:00:03
   ----------------------- ---------------- 7.3/12.3 MB 2.9 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.3 MB 2.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.3 MB 2.6 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.3 MB 2.6 MB/s eta 0:00:02
   ---------------------------- ----------- 8.7/12.3 MB 2.6 MB/s eta 0:00:02
   ---------------------------- ----------- 8.7/12.3 MB 2.6 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.3 MB 2.4 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.3 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 10.5/12.3 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 2.3 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 1.7 MB/s  0:00:07
Downloading tokenizers-0.23.2-cp310-abi3-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ---------- ----------------------------- 0.8/2.9 MB 907.1 kB/s eta 0:00:03
   ------------------ --------------------- 1.3/2.9 MB 1.3 MB/s eta 0:00:02
   --------------------- ------------------ 1.6/2.9 MB 1.4 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.9 MB 1.5 MB/s eta 0:00:01
   -------------------------------- ------- 2.4/2.9 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 1.6 MB/s  0:00:02
Using cached safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Installing collected packages: safetensors, hf-xet, huggingface-hub, tokenizers, transformers, sentence-transformers

   ---------------------------------------- 0/6 [safetensors]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   ------------- -------------------------- 2/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [tokenizers]
   -------------------- ------------------- 3/6 [tokenizers]
   -------------------- ------------------- 3/6 [tokenizers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]
   -------------------------- ------------- 4/6 [transformers]

In [7]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN

model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(df['log_message'].tolist())

c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Moolya\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 12889.76it/s]

In [10]:
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='euclidean')
clusters = dbscan.fit_predict(embeddings)

df['cluster'] = clusters

In [11]:
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,3

In [12]:
df.cluster.unique()

array([   0,    1,    2, ..., 1061, 1062, 1063], dtype=int64)

In [13]:
cluster_counts=df['cluster'].value_counts()
largest_clusters = cluster_counts[cluster_counts > 10].index

for cluster in largest_clusters:
    cluster_logs = df[df['cluster'] == cluster]
    print(f"Cluster {cluster}:")
    print(cluster_logs['log_message'].head(5).to_string(index=False))
    print("\n")

Cluster 0:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-d4f8d0c2-4f...
nova.osapi_compute.wsgi.server [req-6fe0e366-f2...
nova.osapi_compute.wsgi.server [req-945d1f31-a2...


Cluster 4:
nova.osapi_compute.wsgi.server [req-f0bffbc3-5a...
nova.osapi_compute.wsgi.server [req-5e6e042b-f9...
nova.osapi_compute.wsgi.server [req-4d05bae9-8a...
nova.osapi_compute.wsgi.server [req-9174a757-01...
nova.osapi_compute.wsgi.server [req-b2ffcdcc-26...


Cluster 3:
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...
nova.osapi_compute.wsgi.server [req-2bf7cfee-a2...
nova.osapi_compute.wsgi.server [req-5f1c2027-e1...
nova.osapi_compute.wsgi.server [req-4e83daf7-a2...
nova.osapi_compute.wsgi.server [req-fe9ef402-d3...


Cluster 12:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.


Cluster 50:
nova.metadata.wsgi.server [req-7d3eeb2d-3948-43...
nova.metadata.wsgi.server [-] 10.11.21.137,10.1...
nova.metadata.wsgi.server [req-e0d4ce94-e0cb-41...
nova.metadata.wsgi.server [req-c1795e2c-0a17-4a...
nova.metadata.wsgi.server [req-81a97e64-19c0-4f...


Cluster 67:
Backup ended at 2025-08-08 13:06:23.
Backup ended at 2025-06-01 06:27:38.
Backup ended at 2025-11-16 08:17:13.
Backup ended at 2025-07-18 17:06:54.
Backup ended at 2025-08-18 14:29:26.


Cluster 58:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.


Cluster 46:
nova.metadata.wsgi.server [req-61196723-e034-48...
nova.metadata.wsgi.server [req-ecbd525f-38ad-49...
nova.metadata.wsgi.server [req-89545a1f-55c0-44...
nova.metadata.wsgi.server [req-624c74d8-31e8-45...
nova.metadata.wsgi.server [req-410908b9-815e-4f...


Cluster 14:
nova.osapi_compute.wsgi.server [req-033d97b9-69...
nova.osapi_compute.wsgi.server [req-d6e9cfb8-d9...
nova.osapi_compute.wsgi.server [req-8c36e637-8e...
nova.osapi_compute.wsgi.server [req-0b7fefce-6f...
nova.osapi_compute.wsgi.server [req-60f50a9d-82...


Cluster 19:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.
Backup started at 2025-01-15 04:36:39.


Cluster 27:
nova.compute.claims [req-72b4858f-049e-49e1-b31...
nova.compute.claims [req-d38f479d-9bb9-4276-968...
nova.compute.claims [req-6a763803-4838-49c7-814...
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-01d570b0-78a7-4719-b7a...


Cluster 39:
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a...
nova.compute.claims [req-01d570b0-78a7-4719-b7a...
nova.compute.claims [req-4b4dd551-26d8-48e2-bd5...
nova.compute.claims [req-d82fab16-60f8-4c9f-bde...
nova.compute.claims [req-72b4858f-049e-49e1-b31...


Cluster 96:
nova.compute.claims [req-9118475d-6e72-48fa-9de...
nova.compute.claims [req-29a09cdb-3169-4c40-8bd...
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-3d26bc3d-373c-4269-b09...
nova.compute.claims [req-6f9ecdfe-481c-4535-9bd...


Cluster 127:
nova.metadata.wsgi.server [req-3a439e39-d7f5-4c...
nova.metadata.wsgi.server [-] 10.11.21.138,10.1...
nova.metadata.wsgi.server [-] 10.11.21.129,10.1...
nova.metadata.wsgi.server [-] 10.11.21.131,10.1...
nova.metadata.wsgi.server [-] 10.11.21.139,10.1...


Cluster 7:
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-9118475d-6e72-48fa-9de...
nova.compute.claims [req-4b4dd551-26d8-48e2-bd5...
nova.compute.claims [req-6f9ecdfe-481c-4535-9bd...
nova.compute.claims [req-01d570b0-78a7-4719-b7a...


Cluster 16:
nova.compute.claims [req-d6986b54-3735-4a42-907...
nova.compute.claims [req-d82fab16-60f8-4c9f-bde...
nova.compute.claims [req-01d570b0-78a7-4719-b7a...
nova.compute.claims [req-98474cd9-61e1-4afe-bd5...
nova.compute.claims [req-d38f479d-9bb9-4276-968...


Cluster 68:
nova.compute.claims [req-868a5460-dbb6-416b-b4c...
nova.compute.claims [req-29a09cdb-3169-4c40-8bd...
nova.compute.claims [req-d82fab16-60f8-4c9f-bde...
nova.compute.claims [req-3d26bc3d-373c-4269-b09...
nova.compute.claims [req-4b4dd551-26d8-48e2-bd5...


Cluster 80:
nova.compute.claims [req-2d658d2c-7eff-414e-a68...
nova.compute.claims [req-4b4dd551-26d8-48e2-bd5...
nova.compute.claims [req-d82fab16-60f8-4c9f-bde...
nova.compute.claims [req-868a5460-dbb6-416b-b4c...
nova.compute.claims [req-97fcea79-42f7-4241-9b9...


Cluster 25:
nova.metadata.wsgi.server [req-27e91939-3ba4-4d...
nova.metadata.wsgi.server [-] 10.11.21.143,10.1...
nova.metadata.wsgi.server [req-705dd9dc-0fad-45...
nova.metadata.wsgi.server [-] 10.11.21.129,10.1...
nova.metadata.wsgi.server [req-7fd3da99-a9b0-4d...


Cluster 15:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...


Cluster 73:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...


Cluster 84:
nova.metadata.wsgi.server [-] 10.11.21.139,10.1...
nova.metadata.wsgi.server [req-e840cb3c-2e87-4b...
nova.metadata.wsgi.server [-] 10.11.21.123,10.1...
nova.metadata.wsgi.server [-] 10.11.21.137,10.1...
nova.metadata.wsgi.server [req-1cbcfc19-86a6-45...


Cluster 218:
nova.osapi_compute.wsgi.server [req-c6d4eab2-e0...
nova.osapi_compute.wsgi.server [req-7c98765b-50...
nova.osapi_compute.wsgi.server [req-c53a921a-16...
nova.osapi_compute.wsgi.server [req-31d09752-6f...
nova.osapi_compute.wsgi.server [req-74b000e1-54...

In [20]:
classify_with_regex("User User123 logged OUT.")

'User Action'

In [21]:
classify_with_regex("Hey how are you?")

In [23]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)
df[df.regex_label.notnull()][['log_message', 'regex_label']].head(10)

                                          log_message          regex_label
7   File data_6169.csv uploaded successfully by us...  System Notification
14  File data_3847.csv uploaded successfully by us...  System Notification
15                     Backup completed successfully.  System Notification
18           Account with ID 5351 created by User634.          User Action
27                           User User685 logged out.          User Action
30             Backup started at 2025-05-14 07:06:55.  System Notification
36           System reboot initiated by user User243.  System Notification
44             Backup started at 2025-02-15 20:00:19.  System Notification
48  File data_7366.csv uploaded successfully by us...  System Notification
50                   System updated to version 3.9.1.  System Notification

In [24]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,3,NaN
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,4,NaN
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,1061,NaN
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,172,NaN
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1062,NaN
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,1063,NaN

In [25]:
print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts() <= 5].index.tolist())

['Workflow Error', 'Deprecation Warning']

In [28]:
df_non_legacy = df_non_regex[df_non_regex.source != 'LegacyCRM']

In [29]:
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())

In [31]:
X = filtered_embeddings
y = df_non_legacy['target_label']
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(filtered_embeddings, y, test_size=0.3, random_state=42)

logistic_model = LogisticRegression(max_iter=1000,random_state=42)
logistic_model.fit(X_train, y_train)

y_pred = logistic_model.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [32]:
%pip install joblib

Requirement already satisfied: joblib in c:\Users\Moolya\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.5.3)
Note: you may need to restart the kernel to use updated packages.

In [33]:
import joblib

joblib.dump(logistic_model, 'logistic_model.pkl')

['logistic_model.pkl']